[package]
name = "mtool-wgui-main"
version = "0.0.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../../crates/mapp" }

mtool-wgui-core = { path = "../core" }

mtool-interactive-wgui = { path = "../../mtool-interactive/wgui" }

[workspace]
members = [
  "../core",
  "../../mtool-interactive/wgui",
  "../../../crates/mtauri-sys"
]

[workspace.package]
version = "0.0.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2021"

[workspace.dependencies]
yew = { version = "*", features = ["csr"] }
yew-router = "*"
js-sys = "*"
web-sys = "*"
wasm-bindgen = { version = "*", features = ["serde-serialize"] }
wasm-bindgen-futures = "*"
serde = { version = "*", features = ["derive"] }
serde-wasm-bindgen = "*"
async-trait = "*"
anyhow = "*"
thiserror = "*"
once_cell = "*"
tracing = "*"
