[package]
name = "mtool-wgui-main"
version = "0.0.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../../crates/mapp" }
mtool-wgui = { path = "../" }
mtool-cmder = { path = "../../mtool-cmder" }
mtool-interactive = { path = "../../mtool-interactive" }
mtool-proxy = { path = "../../mtool-proxy" }
mtool-translate = { path = "../../mtool-translate" }
mtool-dict = { path = "../../mtool-dict" }
mtool-pdf = { path = "../../mtool-pdf" }

console_error_panic_hook = "*"
