[watch]
watch = [
  "../../../"
]

[serve]
address = "127.0.0.1"
port = 18188

[tools]
wasm_bindgen = "0.2.87"

[[hooks]]
stage = "build"
command = "tailwindcss.cmd"
command_arguments = ["-i", "assets/style.css", "-o", "dist/.stage/tailwind.css"]
