[watch]
watch = [
  "../../../"
]

[serve]
address = "127.0.0.1"
port = 18188

[tools]
wasm_bindgen = "0.2.87"

[build]
pattern_script = '''
<script type="module">
  import init, { run } from '{base}{js}';
  let __MTOOL__ = await init();
  window.__MTOOL__ = __MTOOL__;
  run();
</script>
'''
