[package]
name = "mcloud-api"
version = "0.1.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
base64 = "0.13"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
digest = "0.10"
hmac = "0.12"
sha2 = "0.10"

regex = "1.5"

tokio = { version = "1" }
anyhow = "1.0"
thiserror = "1.0"
