[package]
name = "mcloud-api"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../mapp" }

thiserror = { workspace = true }

hex = "0.4"
base64 = "0.13"
chrono = "0.4"
digest = "0.10"
hmac = "0.12"
sha2 = "0.10"
md5 = "*"
lazy_static = "*"

# netease
openssl = { version = "*", features = ["aws-lc"] }
isahc = { version = "^1", features = ["cookies"] }
urlqstring = "*"

[dev-dependencies]
test-log = { version = "*", features = ["trace"] }
env_logger = "*"
