[package]
name = "mtool-interactive-webapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mtool-interactive-model = { path = "../model" }

msysev = { path = "../../../crates/msysev" }
mkeybinding = { path = "../../../crates/mkeybinding" }

yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"

js-sys = "0.3"

async-trait = "0.1"

wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"

gloo-console = "0.2"
gloo-utils = "0.1"

tracing = "0.1"
tracing-subscriber = { version = "0.3" }
tracing-web = "0.1"

html-escape = "0.2"

anyhow = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
  "KeyboardEvent",
  "ScrollIntoViewOptions",
  "ScrollLogicalPosition"
]

[workspace]
