[package]
name = "my-tool"
version = "0.1.0"
description = "my-tool"
license = "MIT OR Apache-2.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "0.2.22", features = ["full"]}
soup = "0.5.0"
reqwest = {version = "0.10.8", features = ["json"]}
clap = "3.0.0-beta.1"
regex = "1.3.9"
html5ever = "0.25.1"
colored = "2.0.0"
serde_json = "1.0.57"
serde = {version = "1.0.116", features = ["derive"]}