[workspace]

members = [
  "crates/manki-api",
  "crates/mapp",
  "crates/mcloud-api",
  "crates/mdict",
  "crates/minject",
  "crates/mkeybinding",
  "crates/msysev",
  "crates/mproxy",
  "crates/mtauri-sys",

  "modules/mtool-core",
  "modules/mtool-system",
  "modules/mtool-cmder",
  "modules/mtool-dict",
  "modules/mtool-toast",
  "modules/mtool-translate",
  "modules/mtool-interactive",
  "modules/mtool-wgui",
  "mtool",
]

[workspace.dependencies]
tracing = "0.1"

tokio = "1"
async-trait = "0.1"
futures = "0.3"

thiserror = "1.0"
anyhow = "1.0"

