[package]
name = "my-tool"
version = "0.1.0"
description = """
my tool
"""
license = "MIT OR Apache-2.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
"crates/anki",
"crates/hjdict",
"crates/translate"
]

[dependencies]
anki = {path = "crates/anki"}
hjdict = {path = "crates/hjdict"}
translate = {path = "crates/translate"}
tokio = {version = "0.2.22", features = ["full"]}
futures = "0.3"
clap = "3.0.0-beta.2"
gio = "0.9.1"
gtk = "0.9.2"

# clap_generate = "3.0.0-beta.2"