[workspace]

resolver = "2"

members = [
  "crates/mapp",
  # "crates/mcloud-api",
  # "crates/mdict",
  # "crates/msysev",
  # "crates/mkeybinding",
  # "crates/manki-api",
  # "crates/mproxy",

  # "modules/mtool-core",
  # "modules/mtool-system",
  # # "modules/mtool-rpc",
  # "modules/mtool-p2p",
  # "modules/mtool-storage",
  # "modules/mtool-dioxus",
  # "modules/mtool-cmdpal",
  # "modules/mtool-apps",
  # "modules/mtool-assistant",
  # "modules/mtool-proxy",
  # "modules/mtool-emacs",
  # # "modules/mtool-pdf",
  
  # "mtool",
]

[workspace.package]
version = "0.0.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2024"

[workspace.dependencies]
# TODO: macro re-export support
dioxus = { version = "0.7" }
dioxus-desktop = { version = "0.7" }
dioxus-asset-resolver = { version = "0.7" }

bevy = { version = "0.16.1" }
ouroboros = "*"
clap = { version = "*", features = ["derive", "cargo", "string"] }
sea-orm = "*"
sea-orm-migration = "*"
thiserror = "*"

pyo3 = { version = "*", features = ["auto-initialize", "abi3-py313", "generate-import-lib"] }
pyo3-async-runtimes = { version = "*", features = ["attributes", "tokio-runtime"] }

# NOTE: platform custom features
web-sys = "*"
windows = "*"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.android-dev]
inherits = "dev"
