[package]
name = "my-tool"
version = "0.1.0"
description = """
my tool
"""
license = "MIT OR Apache-2.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
"crates/anki",
"crates/hjdict",
]

[dependencies]
anki = {version = "0.1.0", path = "crates/anki"}
hjdict = {version = "0.1.0", path = "crates/hjdict"}
tokio = {version = "0.2.22", features = ["full"]}
futures = "0.3"
clap = "2.33.3"

