[package]
name = "my-tool"
version = "0.1.0"
description = """
my tool
"""
license = "MIT OR Apache-2.0"
authors = ["yydcnjjw <yydcnjjw@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
"crates/*",
]

[dependencies]
syn = "=1.0.57"
anki = {path = "crates/anki"}
hjdict = {path = "crates/hjdict"}
translate = {path = "crates/translate"}
search = {path = "crates/search"}
tokio = {version = "*", features = ["full"]}
futures = "*"
clap = "3.0.0-beta.2"
# clap_generate = "3.0.0-beta.2"
cpp_core = "0.6.0"
qt_core = "0.5.0"
qt_gui = "0.5.0"                                                                       
qt_qml = "0.5.0"
qt_widgets = "0.5.0"

[build-dependencies]                                                                            
qt_ritual_build = "0.5.0"
