[package]
name = "main"
version = "0.1.0"
authors = ["jiangjw <jiangjw@koal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
clap = "2.33.3"