[package]
name = "mtool-toast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }

mtool-core = { path = "../mtool-core" }

mtool-cmder = { path = "../mtool-cmder" }

notify-rust = { version = "4", default-features = false }

clap = { version = "4", features = ["derive"] }

log = "0.4"

tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

anyhow = "1.0"
