[package]
name = "mtool-emacs"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
graphic = [ "mtool-system/graphic" ]

[dependencies]
mapp = { path = "../../crates/mapp" }

mtool-core = { path = "../mtool-core" }
mtool-p2p = { path = "../mtool-p2p" }
mtool-storage = { path = "../mtool-storage" }
mtool-system = { path = "../mtool-system" }

emacs = "*"


