[package]
name = "mtool"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "desktop" ]

mobile = []

desktop = []

dynamic_linking = [ "mtool-dioxus/dynamic_linking" ]

[dependencies]
mapp = { path = "../crates/mapp" }
mtool-core = { path = "../modules/mtool-core" }
mtool-system = { path = "../modules/mtool-system" }
mtool-storage = { path = "../modules/mtool-storage" }
mtool-dioxus = { path = "../modules/mtool-dioxus" }
mtool-cmdpal = { path = "../modules/mtool-cmdpal" }
# mtool-pdf = { path = "../modules/mtool-pdf" }
# mtool-assistant = { path = "../modules/mtool-assistant" }
mtool-proxy = { path = "../modules/mtool-proxy" }
# mtool-wgui = { path = "../modules/mtool-wgui" }
# mtool-main-window = { path = "../modules/mtool-main-window" }
# mtool-cmder = { path = "../modules/mtool-cmder" }
# mtool-translate = { path = "../modules/mtool-translate" }
# mtool-dict = { path = "../modules/mtool-dict" }
# mtool-interactive = { path = "../modules/mtool-interactive" }
# mtool-proxy = { path = "../modules/mtool-proxy" }
# mtool-toast = { path = "../modules/mtool-toast" }
# mtool-ai = { path = "../modules/mtool-ai" }

# mtool-storage = { path = "../modules/mtool-storage" }

# tauri = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
mtool-apps = { path = "../modules/mtool-apps" }

[build-dependencies]
# tauri-build = { version = "*", features = ["codegen"] }
