[package]
name = "mtool"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "desktop" ]

system = [
  "mtool-core/python",
  "dep:mtool-system",
  "dep:mtool-emacs",
]

graphic = [
  "system",
  "dep:mtool-dioxus",
]

mobile = [
  "graphic",
  "mtool-assistant/mobile",
]

desktop = [
  "graphic",
  "dep:mtool-cmdpal",
  "mtool-assistant/desktop",
  "dep:mtool-proxy",
  "dep:mtool-apps",
]

server = [
  "mtool-p2p/server",
  "mtool-storage/server",
]

emacs = [
   "system",
   "dep:mtool-emacs",
   "dep:mtool-proxy",
]

bevy = [
  "mtool-dioxus/bevy",
  "mtool-assistant/bevy"
]

bevy_dynamic_linking = [ "mtool-dioxus/bevy_dynamic_linking" ]

[dependencies]
mapp = { path = "../crates/mapp" }
mtool-core = { path = "../modules/mtool-core" }
mtool-p2p = { path = "../modules/mtool-p2p" }
mtool-storage = { path = "../modules/mtool-storage" }

mtool-dioxus = { path = "../modules/mtool-dioxus", optional = true }
mtool-system = { path = "../modules/mtool-system", optional = true }
mtool-emacs = { path = "../modules/mtool-emacs", optional = true }

mtool-cmdpal = { path = "../modules/mtool-cmdpal", optional = true }
mtool-assistant = { path = "../modules/mtool-assistant", optional = true }
mtool-proxy = { path = "../modules/mtool-proxy", optional = true }
mtool-apps = { path = "../modules/mtool-apps", optional = true }

[build-dependencies]

