[package]
name = "mtool-dioxus"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
native = [
  "dioxus/native",
  "dep:dioxus-native",
]

webview = [
  "dioxus/desktop",
  "dep:dioxus-desktop",
]

bevy = [ "dep:bevy" ]
bevy_dynamic_linking = [ "bevy?/dynamic_linking" ]

[dependencies]
mapp = { path = "../../crates/mapp", features = ["web"] }
mkeybinding = { path = "../../crates/mkeybinding" }

mtool-core = { path = "../mtool-core" }
mtool-storage = { path = "../mtool-storage" }

winit = "*"
dioxus = { workspace = true, features = ["router"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components" }
blake3 = { version = "1.5", features = ["pure"] } # use pure for fix compile error
route-recognizer = "*"
infer = "*"
urlencoding = "*"

bevy = { workspace = true, optional = true }

[dependencies.dioxus-free-icons]
version = "0.10.0-alpha.1"
features = [
  "octicons",
  "font-awesome-brands",
  "font-awesome-regular",
  "font-awesome-solid"
]

[dependencies.dioxus-desktop]
workspace = true
optional = true

[dependencies.dioxus-native]
workspace = true
optional = true
