[package]
name = "mtool-wgui"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
custom-protocol = [ "tauri/custom-protocol" ]

[dependencies]
mapp = { path = "../../crates/mapp" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mkeybinding = { path = "../../crates/mkeybinding" }
msysev = { path = "../../crates/msysev" }

tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde-error = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
tracing = { workspace = true }
dashmap = {  workspace = true }
once_cell = { workspace = true }
cfg-if = { workspace = true }
send_wrapper = { workspace = true }
yew = { workspace = true, features = ["csr"] }
yew-router = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
html-escape = { workspace = true }

route-recognizer = "*"

[dependencies.web-sys]
workspace = true
features = [
  "KeyboardEvent",
  "ResizeObserver",
  "ResizeObserverEntry",
  "HtmlDivElement",
  "Screen",
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
msysev = { path = "../../crates/msysev" }
mkeybinding = { path = "../../crates/mkeybinding" }
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }

tauri = { workspace = true, features = ["system-tray"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios", target_family = "wasm")))'.dependencies]
tauri-plugin-global-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-window = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }

[target.'cfg(not(target_family = "wasm"))'.build-dependencies]
tauri-build = { workspace = true }
