[package]
name = "mtool-wgui"
version.workspace = true
authors.workspace = true
edition.workspace = true
# links = "mtool-wgui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
custom-protocol = [ "tauri/custom-protocol" ]
devtools = [ "tauri/devtools" ]

[dependencies]
mapp = { path = "../../crates/mapp", features = ["web"] }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mkeybinding = { path = "../../crates/mkeybinding" }
msysev = { path = "../../crates/msysev" }

send_wrapper = "*"
yew = { workspace = true }
yew-autoprops = { workspace = true }
yew-router = { workspace = true }
html-escape = "*"
js-sys = "*"
route-recognizer = "*"
gloo-utils = "*"
gloo-events = "*"
grass = "*"

[dependencies.web-sys]
workspace = true
features = [
  "KeyboardEvent",
  "ResizeObserver",
  "ResizeObserverEntry",
  "HtmlDivElement",
  "Screen"
]


[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }

tauri = { workspace = true, features = ["tray-icon"] }
tauri-plugin = { workspace = true }
tauri-utils = { version = "2.*" }
tauri-runtime-wry = { version = "2.*" }
raw-window-handle = "0.6"
raw-window-handle5 = { version = "0.5", package = "raw-window-handle" }

[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
]

[target.'cfg(not(any(target_os = "android", target_os = "ios", target_family = "wasm")))'.dependencies]
tauri-plugin-global-shortcut = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-os = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
