[package]
name = "mtool-system"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-core = { path = "../mtool-core" }
mtool-p2p = { path = "../mtool-p2p" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-future = { version = "0.2", features = [ "std" ] }

[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
]

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client = "*"
wayland-protocols-wlr = { version = "*", features = ["client"] }

[target.'cfg(target_os = "linux")'.dependencies.x11rb-async]
version = "*"
features = [
  "allow-unsafe-code",
  "extra-traits",
  "record",
  "xkb",
]

[target.'cfg(target_os = "android")'.dependencies]
mtool-dioxus = { path = "../mtool-dioxus" }
