[package]
name = "mtool-system"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
msysev = { path = "../../crates/msysev", features = ["event-loop"] } # for event module
mkeybinding = { path = "../../crates/mkeybinding" } # for keybinding module
mtool-core = { path = "../mtool-core" }

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "4", default-features = false, features = ["tokio"] }
