[package]
name = "mtool-system"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
msysev = { path = "../../crates/msysev" } # for event module
mkeybinding = { path = "../../crates/mkeybinding" } # for keybinding module
mtool-core = { path = "../mtool-core" }

tokio = { workspace = true }
async-trait = { workspace = true }
tauri = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_DataExchange",
  "Win32_System_LibraryLoader",
]
