[package]
name = "mtool-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-core = { path = "../mtool-core" }

# for event module
msysev = { path = "../../crates/msysev" }

# for keybinding module
mkeybinding = { path = "../../crates/mkeybinding" }

# async
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

tauri = { version = "1", features = ["api-all"] }

# error handle
anyhow = "1.0"
thiserror = "1.0"

tracing = "0.1"

clap = { version = "4", features = ["derive", "cargo"] }

serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies]
[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.48"
features = [
  "Win32_Foundation",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_DataExchange",
  "Win32_System_LibraryLoader",
]
