[package]
name = "minject"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minject-macro = { path = "./macro" }

thiserror = "*"
anyhow = "*"
futures = "*"

[dev-dependencies]
tokio = { version = "*", features = ["rt", "macros"] }
