[package]
name = "mtool-interactive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
mtool-interactive-model = { path = "./model" }

mapp = { path = "../../crates/mapp" }

mtool-core = { path = "../mtool-core" }

mtool-system = { path = "../mtool-system" }

tauri = { version = "1", features = ["api-all"] }

log = "0.4"

tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

anyhow = "1.0"
serde-error = "0.1"

clap = { version = "4", features = ["derive"] }

futures = "0.3"

itertools = "0.10"
