[package]
name = "mtool-interactive"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-interactive-model = { path = "./model" }
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }
mtool-wgui = { path = "../mtool-wgui" }

tauri = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
serde-error = { workspace = true }
fuzzy-matcher = { workspace = true }

rand = "0.8"
