[package]
name = "mtool-interactive"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }

tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde-error = { workspace = true }
serde-wasm-bindgen = { workspace = true }
yew = { workspace = true }
cfg-if = { workspace = true }
fuzzy-matcher = { workspace = true }
yew-router = { workspace = true }
grass = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

gloo-utils = "0.1"
html-escape = "0.2"
rand = "0.8"

[dependencies.web-sys]
workspace = true
features = [
  "ScrollIntoViewOptions",
  "ScrollLogicalPosition"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }

tauri = { workspace = true }
clap = { workspace = true }
