[package]
name = "mtool-interactive"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "mtool-interactive"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp", features = ["web"] }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-main-window = { path = "../mtool-main-window" }
mtool-cmder = { path = "../mtool-cmder" }

yew = { workspace = true }
yew-router = { workspace = true }

fuzzy-matcher = "*"
shellwords = "*"

[dependencies.web-sys]
workspace = true
features = [
  "ScrollIntoViewOptions",
  "ScrollLogicalPosition"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }

tauri = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true }
