[package]
name = "sysev-mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# service = ["msysev"]
service = []

[dependencies]
mrpc = { path = "../../../mrpc/mrpc" }
anyhow = "1.0"
log = "0.4"
tokio = { version = "1", default_features = false }

# msysev = { path = "../../crates/msysev", optional = true }
msysev = { path = "../../crates/msysev" }
