[package]
name = "mtool-proxy"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mproxy = { path = "../../crates/mproxy" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-core = { path = "../mtool-core" }
mtool-interactive = { path = "../mtool-interactive" }

tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
notify-rust = { workspace = true }
