[package]
name = "mtool-proxy"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "mtool-proxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mproxy = { path = "../../crates/mproxy" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-main-window = { path = "../mtool-main-window" }
mtool-interactive = { path = "../mtool-interactive" }

yew = { workspace = true }
yew-router = { workspace = true }

async-stream = "*"

[dependencies.web-sys]
workspace = true

[dependencies.yew_icons]
workspace = true
features = [
  "OcticonsDownload16",
  "OcticonsUpload16"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }
mtool-cmder = { path = "../mtool-cmder" }

tauri = { workspace = true }
clap = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true }
