[package]
name = "mtool-ai"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-core = { path = "../mtool-core" }
mllama-sys = { path = "../../crates/mllama-sys" }

serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.0" }
