[package]
name = "sysev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "*", features = ["derive"], optional=true}
thiserror = "*"
anyhow = "*"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = {version = "*", features = ["xlib", "xrecord"]}
xproto = "*"
