use crate::event::{KeyAction, KeyCode};
use std::os::raw::{c_uint, c_ulong};
use x11::keysym::*;

pub struct KeySym(pub c_uint);

impl KeySym {
    pub fn new(v: c_ulong) -> Self {
        Self(c_uint::try_from(v).unwrap())
    }
}

impl From<KeySym> for KeyCode {
    fn from(v: KeySym) -> Self {
        match v.0 {
            XK_grave => KeyCode::GraveAccent,
            XK_1 => KeyCode::Num1,
            XK_2 => KeyCode::Num2,
            XK_3 => KeyCode::Num3,
            XK_4 => KeyCode::Num4,
            XK_5 => KeyCode::Num5,
            XK_6 => KeyCode::Num6,
            XK_7 => KeyCode::Num7,
            XK_8 => KeyCode::Num8,
            XK_9 => KeyCode::Num9,
            XK_0 => KeyCode::Num0,
            XK_minus => KeyCode::Minus,
            XK_equal => KeyCode::Equal,
            XK_BackSpace => KeyCode::BackSpace,
            XK_Tab => KeyCode::Tab,
            XK_q => KeyCode::Q,
            XK_w => KeyCode::W,
            XK_e => KeyCode::E,
            XK_r => KeyCode::R,
            XK_t => KeyCode::T,
            XK_y => KeyCode::Y,
            XK_u => KeyCode::U,
            XK_i => KeyCode::I,
            XK_o => KeyCode::O,
            XK_p => KeyCode::P,
            XK_bracketleft => KeyCode::BracketLeft,
            XK_bracketright => KeyCode::BracketRight,
            XK_backslash => KeyCode::Backslash,
            XK_Caps_Lock => KeyCode::CapsLock,
            XK_a => KeyCode::A,
            XK_s => KeyCode::S,
            XK_d => KeyCode::D,
            XK_f => KeyCode::F,
            XK_g => KeyCode::G,
            XK_h => KeyCode::H,
            XK_j => KeyCode::J,
            XK_k => KeyCode::K,
            XK_l => KeyCode::L,
            XK_semicolon => KeyCode::Semicolon,
            XK_apostrophe => KeyCode::Apostrophe,
            // NonUS,
            XK_Return => KeyCode::Return,
            XK_Shift_L => KeyCode::LeftShift,
            // NonUS2,
            XK_z => KeyCode::Z,
            XK_x => KeyCode::X,
            XK_c => KeyCode::C,
            XK_v => KeyCode::V,
            XK_b => KeyCode::B,
            XK_n => KeyCode::N,
            XK_m => KeyCode::M,
            XK_comma => KeyCode::Comma,
            XK_period => KeyCode::Period,
            XK_slash => KeyCode::Slash,
            // Internation1,
            XK_Shift_R => KeyCode::RightShift,
            XK_Control_L => KeyCode::LeftControl,
            XK_Alt_L => KeyCode::LeftAlt,
            XK_space => KeyCode::Spacebar,
            XK_Alt_R => KeyCode::RightAlt,
            XK_Control_R => KeyCode::RightControl,
            XK_Insert => KeyCode::Insert,
            XK_Delete => KeyCode::Delete,
            XK_leftarrow => KeyCode::LeftArrow,
            XK_Home => KeyCode::Home,
            XK_End => KeyCode::End,
            XK_uparrow => KeyCode::UpArrow,
            XK_downarrow => KeyCode::DownArrow,
            XK_Page_Up => KeyCode::PageUp,
            XK_Page_Down => KeyCode::PageDown,
            XK_rightarrow => KeyCode::RightArrow,
            XK_Num_Lock => KeyCode::NumLock,
            XK_KP_7 => KeyCode::Keypad7,
            XK_KP_4 => KeyCode::Keypad4,
            XK_KP_1 => KeyCode::Keypad1,
            XK_KP_Divide => KeyCode::Divide,
            XK_KP_8 => KeyCode::Keypad8,
            XK_KP_5 => KeyCode::Keypad5,
            XK_KP_2 => KeyCode::Keypad2,
            XK_KP_0 => KeyCode::Keypad0,
            XK_KP_Multiply => KeyCode::Multiply,
            XK_KP_9 => KeyCode::Keypad9,
            XK_KP_6 => KeyCode::Keypad6,
            XK_KP_3 => KeyCode::Keypad3,
            // _ => KeypadPeriod,
            XK_KP_Subtract => KeyCode::Subtract,
            XK_KP_Add => KeyCode::Add,
            // _ => KeypadComma,
            XK_KP_Enter => KeyCode::KeypadEnter,
            XK_Escape => KeyCode::Escape,
            XK_F1 => KeyCode::F1,
            XK_F2 => KeyCode::F2,
            XK_F3 => KeyCode::F3,
            XK_F4 => KeyCode::F4,
            XK_F5 => KeyCode::F5,
            XK_F6 => KeyCode::F6,
            XK_F7 => KeyCode::F7,
            XK_F8 => KeyCode::F8,
            XK_F9 => KeyCode::F9,
            XK_F10 => KeyCode::F10,
            XK_F11 => KeyCode::F11,
            XK_F12 => KeyCode::F12,
            XK_Print => KeyCode::PrintScreen,
            XK_Scroll_Lock => KeyCode::ScrollLock,
            XK_Pause => KeyCode::Pause,
            XK_Super_L => KeyCode::LeftGUI,
            XK_Super_R => KeyCode::RightGUI,
            XK_Menu => KeyCode::Application,
            _ => KeyCode::Unknown,
        }
    }
}
