[package]
name = "mtool-dict"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "mtool-dict"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-main-window = { path = "../mtool-main-window" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-interactive = { path = "../mtool-interactive" }

yew = { workspace = true }
ouroboros = { workspace = true }

[dependencies.yew_icons]
workspace = true
features = [
  "FontAwesomeSolidCircleNotch"
]

[dependencies.web-sys]
workspace = true
features = [
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mdict = { path = "../../crates/mdict" }
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }

tauri = { workspace = true }

sea-orm = { version = "*", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
clipboard = "*"

[build-dependencies]
tauri-plugin = { workspace = true }
