[package]
name = "mtool-wgui-core"
version = "0.1.0"
edition = "2021"
workspace = "../wmain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../../crates/mapp" }
mtauri-sys = { path = "../../../crates/mtauri-sys" }

yew = { workspace = true }
yew-router = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }

route-recognizer = "*"

[dependencies.web-sys]
workspace = true
features = [
  "ResizeObserver",
  "ResizeObserverEntry",
  "HtmlDivElement",
  "Screen",
]
