[package]
name = "mtool-wgui-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../../crates/mapp" }

mtauri-sys = { path = "../../../crates/mtauri-sys" }

yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"

js-sys = "0.3"
web-sys = "0.3"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }

async-trait = "0.1"

anyhow = "1.0"
thiserror = "1.0"

route-recognizer = "0.3"

once_cell = "1"

tracing = "0.1"

[workspace]
