[package]
name = "mdict"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../mapp" }

thiserror = { workspace = true }

quick-xml = { version = "*", features = ["serialize"] }
flate2 = "1.0"
minilzo-rs = "*"
ripemd128 = "0.1"
byteorder = "1.4"
multimap = "0.8.3"
scraper = "0.12"
selectors = "0.22"
