[package]
name = "mtool-cmder"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "mtool-cmder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }

tabled = "*"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }

clap = { workspace = true }
