[package]
name = "mproxy"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
mapp = { path = "../mapp" }

protobuf = "*"
weak-table = "*"
hyper = { version = "*", features = ["full"] }
hyper-util = { version = "*", features = ["tokio"] }
http-body-util = "*"
socksv5 = "*"
strum = { version = "*", features = ["derive"] }
enum_dispatch = "*"
domain_matcher = { git = "https://github.com/Qv2ray/DomainMatcher" }
warp = "*"
rustls = { version = "*" }
rustls-pemfile = "*"
rustls-pki-types = "*"
tokio-rustls = { version = "*" }
tokio_kcp = "*"

[dependencies.quinn]
version = "*"
default-features = false
features = [
  "log",
  "rustls-aws-lc-rs",
  "platform-verifier",
  "runtime-tokio",
  "bloom",  
]

[build-dependencies]
protobuf-codegen = "*"
protobuf = "*"

[dev-dependencies]
tracing-test = "*"
