[package]
name = "mproxy"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
mapp = { path = "../mapp" }

protobuf = "*"
weak-table = "*"
quinn = { version = "*" }
hyper = { version = "*", features = ["full"] }
hyper-util = { version = "*", features = ["tokio"] }
http-body-util = "*"
socksv5 = "*"
strum = { version = "*", features = ["derive"] }
enum_dispatch = "*"
domain_matcher = { git = "https://github.com/Qv2ray/DomainMatcher" }
warp = "*"
rustls = { version = "*", default-features = false, features = ["ring", "logging", "std", "tls12"] }
rustls-pemfile = "*"
rustls-pki-types = "*"
tokio-rustls = { version = "*", default-features = false, features = ["ring", "logging", "tls12"] }
tokio_kcp = "*"

[build-dependencies]
protobuf-codegen = "*"
protobuf = "*"

[dev-dependencies]
tracing-test = "*"
