[package]
name = "mtool-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }

# cmdline
clap = { workspace = true }

# config
dirs = "*"

# logger
time = { version = "0.3.20", features = ["formatting"] }

# rpc
tonic = "*"
prost = "*"
