[package]
name = "mtool-translate"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mcloud-api = { path = "../../crates/mcloud-api" }
mllama-sys = { path = "../../crates/mllama-sys" }
mtool-core = { path = "../mtool-core" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-system = { path = "../mtool-system" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-interactive = { path = "../mtool-interactive" }

serde = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
itertools = { workspace = true }
