[package]
name = "mtool-translate"
version.workspace = true
authors.workspace = true
edition.workspace = true
links = "mtool-translate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-main-window = { path = "../mtool-main-window" }

yew = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  "HtmlTextAreaElement"
]

[dependencies.yew_icons]
workspace = true
features = [
  "FontAwesomeSolidCircleNotch"
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mcloud-api = { path = "../../crates/mcloud-api" }
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-interactive = { path = "../mtool-interactive" }
# mtool-ai = { path = "../mtool-ai" }

tauri = { workspace = true }
clap = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true }
