[package]
name = "mtool-translate"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtauri-sys = { path = "../../crates/mtauri-sys" }
mtool-wgui = { path = "../mtool-wgui" }

async-trait = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
itertools = { workspace = true }
clap = { workspace = true }
cfg-if = { workspace = true }
yew = { workspace = true }
tracing = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  "HtmlTextAreaElement"
]

[dependencies.yew_icons]
workspace = true
features = [
  "OcticonsDownload16",
  "OcticonsUpload16"
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mcloud-api = { path = "../../crates/mcloud-api" }
mtool-core = { path = "../mtool-core" }
mtool-system = { path = "../mtool-system" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-interactive = { path = "../mtool-interactive" }
mtool-ai = { path = "../mtool-ai" }

clap = { workspace = true }
tokio = { workspace = true }
tauri = { workspace = true }
serde-error = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["sync", "rt"] }
