[package]
name = "mtool-storage"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-core = { path = "../mtool-core" }
mtool-rpc = { path = "../mtool-rpc" }

# rpc
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }

# sqlite
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }

# key-value local storage
kv = "*"

# CRDT
loro = "*"

[build-dependencies]
tonic-prost-build = { workspace = true }
