[package]
name = "mtool-assistant"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
desktop = []

mobile = []

bevy = [
  "dep:bevy",
  "dep:bevy-inspector-egui",
  "dep:smooth-bevy-cameras"
]

[dependencies]
mapp = { path = "../../crates/mapp" }

mtool-core = { path = "../mtool-core" }
mtool-dioxus = { path = "../mtool-dioxus" }
mtool-cmdpal = { path = "../mtool-cmdpal" }
mtool-system = { path = "../mtool-system" }
mtool-rpc = { path = "../mtool-rpc" }
mtool-p2p = { path = "../mtool-p2p" }
mtool-storage = { path = "../mtool-storage" }

dioxus = { workspace = true }
dioxus-asset-resolver = { workspace = true }

open = "*"

# notify
include_dir = "*"
rodio = { version = "0.20", features = ["symphonia-all"] }
chrono = "*"

# rpc
tonic = { workspace = true }
prost = { workspace = true }
tonic-prost = { workspace = true }

# bevy
bevy = { workspace = true, features = ["bevy_dev_tools"], optional = true }
bevy-inspector-egui = { version = "*", optional = true }
smooth-bevy-cameras = { version = "*", optional = true }

# music
mcloud-api = { path = "../../crates/mcloud-api" }
rsubs-lib = "*"
time = "*"

# ai agent
markdown = "*"

pyo3 = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies.windows]
workspace = true
features = [
  "Foundation",
  "Foundation_Collections",
  "Storage_Streams",
  "Media_Core",
  "Media_Control",
  "Media_Playback",
]

[build-dependencies]
tonic-prost-build = { workspace = true }
