[package]
name = "mtool-pdf"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapp = { path = "../../crates/mapp" }
mtool-cmder = { path = "../mtool-cmder" }
mtool-wgui = { path = "../mtool-wgui" }
mtool-interactive = { path = "../mtool-interactive" }

clap = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
yew = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
cfg-if = { workspace = true }
send_wrapper = { workspace = true }
web-sys = { workspace = true, features = ["HtmlCanvasElement", "CanvasRenderingContext2d", "ImageData"] }
js-sys = { workspace = true }

pdfium-render = "0.8.6"


[target.'cfg(not(target_family = "wasm"))'.dependencies]
mtool-core = { path = "../mtool-core" }

tauri = { workspace = true }
